// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCROyVfAIx6aItlUrH6kk5x1Cp1hKONQMw',
    appId: '1:526698611691:web:ef467dbd1e1189859b0fae',
    messagingSenderId: '526698611691',
    projectId: 'chat-app-867ac',
    authDomain: 'chat-app-867ac.firebaseapp.com',
    storageBucket: 'chat-app-867ac.appspot.com',
    measurementId: 'G-5NGNZHQ2F7',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB9BFWhuR2rkyEIii4Dv6OpJpZvXfUYCfE',
    appId: '1:526698611691:android:b9ff3fd3f29d278f9b0fae',
    messagingSenderId: '526698611691',
    projectId: 'chat-app-867ac',
    storageBucket: 'chat-app-867ac.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB5lwg9GwNJYsEKpKuMhons7NoBmK5Rbg8',
    appId: '1:526698611691:ios:63d084861eecf0b79b0fae',
    messagingSenderId: '526698611691',
    projectId: 'chat-app-867ac',
    storageBucket: 'chat-app-867ac.appspot.com',
    iosBundleId: 'com.example.chatMe',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyB5lwg9GwNJYsEKpKuMhons7NoBmK5Rbg8',
    appId: '1:526698611691:ios:63d084861eecf0b79b0fae',
    messagingSenderId: '526698611691',
    projectId: 'chat-app-867ac',
    storageBucket: 'chat-app-867ac.appspot.com',
    iosBundleId: 'com.example.chatMe',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCROyVfAIx6aItlUrH6kk5x1Cp1hKONQMw',
    appId: '1:526698611691:web:1411dc077c0055289b0fae',
    messagingSenderId: '526698611691',
    projectId: 'chat-app-867ac',
    authDomain: 'chat-app-867ac.firebaseapp.com',
    storageBucket: 'chat-app-867ac.appspot.com',
    measurementId: 'G-MBPVEC6V4B',
  );
}
